// A map to show "closing brackets",
// for example: ), ], }, ...
// Compiled from: http://www.unicode.org/Public/UCD/latest/ucd/BidiBrackets.txt
const closingBrackets = new Set([
  0x0029, // RIGHT PARENTHESIS
  0x005D, // RIGHT SQUARE BRACKET
  0x007D, // RIGHT CURLY BRACKET
  0x0F3B, // TIBETAN MARK GUG RTAGS GYAS
  0x0F3D, // TIBETAN MARK ANG KHANG GYAS
  0x169C, // OGHAM REVERSED FEATHER MARK
  0x2046, // RIGHT SQUARE BRACKET WITH QUILL
  0x207E, // SUPERSCRIPT RIGHT PARENTHESIS
  0x208E, // SUBSCRIPT RIGHT PARENTHESIS
  0x2309, // RIGHT CEILING
  0x230B, // RIGHT FLOOR
  0x232A, // RIGHT-POINTING ANGLE BRACKET
  0x2769, // MEDIUM RIGHT PARENTHESIS ORNAMENT
  0x276B, // MEDIUM FLATTENED RIGHT PARENTHESIS ORNAMENT
  0x276D, // MEDIUM RIGHT-POINTING ANGLE BRACKET ORNAMENT
  0x276F, // HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT
  0x2771, // HEAVY RIGHT-POINTING ANGLE BRACKET ORNAMENT
  0x2773, // LIGHT RIGHT TORTOISE SHELL BRACKET ORNAMENT
  0x2775, // MEDIUM RIGHT CURLY BRACKET ORNAMENT
  0x27C6, // RIGHT S-SHAPED BAG DELIMITER
  0x27E7, // MATHEMATICAL RIGHT WHITE SQUARE BRACKET
  0x27E9, // MATHEMATICAL RIGHT ANGLE BRACKET
  0x27EB, // MATHEMATICAL RIGHT DOUBLE ANGLE BRACKET
  0x27ED, // MATHEMATICAL RIGHT WHITE TORTOISE SHELL BRACKET
  0x27EF, // MATHEMATICAL RIGHT FLATTENED PARENTHESIS
  0x2984, // RIGHT WHITE CURLY BRACKET
  0x2986, // RIGHT WHITE PARENTHESIS
  0x2988, // Z NOTATION RIGHT IMAGE BRACKET
  0x298A, // Z NOTATION RIGHT BINDING BRACKET
  0x298C, // RIGHT SQUARE BRACKET WITH UNDERBAR
  0x298E, // RIGHT SQUARE BRACKET WITH TICK IN BOTTOM CORNER
  0x2990, // RIGHT SQUARE BRACKET WITH TICK IN TOP CORNER
  0x2992, // RIGHT ANGLE BRACKET WITH DOT
  0x2994, // RIGHT ARC GREATER-THAN BRACKET
  0x2996, // DOUBLE RIGHT ARC LESS-THAN BRACKET
  0x2998, // RIGHT BLACK TORTOISE SHELL BRACKET
  0x29D9, // RIGHT WIGGLY FENCE
  0x29DB, // RIGHT DOUBLE WIGGLY FENCE
  0x29FD, // RIGHT-POINTING CURVED ANGLE BRACKET
  0x2E23, // TOP RIGHT HALF BRACKET
  0x2E25, // BOTTOM RIGHT HALF BRACKET
  0x2E27, // RIGHT SIDEWAYS U BRACKET
  0x2E29, // RIGHT DOUBLE PARENTHESIS
  0x3009, // RIGHT ANGLE BRACKET
  0x300B, // RIGHT DOUBLE ANGLE BRACKET
  0x300D, // RIGHT CORNER BRACKET
  0x300F, // RIGHT WHITE CORNER BRACKET
  0x3011, // RIGHT BLACK LENTICULAR BRACKET
  0x3015, // RIGHT TORTOISE SHELL BRACKET
  0x3017, // RIGHT WHITE LENTICULAR BRACKET
  0x3019, // RIGHT WHITE TORTOISE SHELL BRACKET
  0x301B, // RIGHT WHITE SQUARE BRACKET
  0xFE5A, // SMALL RIGHT PARENTHESIS
  0xFE5C, // SMALL RIGHT CURLY BRACKET
  0xFE5E, // SMALL RIGHT TORTOISE SHELL BRACKET
  0xFF09, // FULLWIDTH RIGHT PARENTHESIS
  0xFF3D, // FULLWIDTH RIGHT SQUARE BRACKET
  0xFF5D, // FULLWIDTH RIGHT CURLY BRACKET
  0xFF60, // FULLWIDTH RIGHT WHITE PARENTHESIS
  0xFF63  // HALFWIDTH RIGHT CORNER BRACKET
]);

export default closingBrackets;
